### ISSUE TITLE
"al/core.hpp" not available in devel

### ISSUE THREAD

**Issue by mantaraya36** [AlloSphere-Research-Group/al_proj#3]
This file seems to have been removed in the devel version. The demo test.cpp file needs to be modified to address this.

**Comment by younkhg** [comment]
oh yes. I removed the file with an idea that we should be explicitly
including the files we only want.

but with this issue we'll have problem running the example files... maybe
put it back for now?

**Comment by mantaraya36** [comment]
I like the idea of only including what you want, we should move forward and
fix this and the examples.

**Comment by younkhg** [comment]
other possibility: we can have handy inclusion files but with smaller list
in narrower domain

al/math.hpp -> vec, random, mat, quat
al/graphics.hpp -> graphics, mesh shape
al/app.hpp ...
al/sphere.hpp ...

something like this?

**Comment by mantaraya36** [comment]
Yes, that sounds good.

**Comment by konhyong** [comment]
Oh yes, I did mention it briefly but should have specified what to change.
right now devel branch has a different folder structure so they have to be manually modified when switching branches.
pushed a change so that it works for devel branch, and added in comments on what to switch for master branch.
the above suggestion sounds good to me as well.
